<a href="https://colab.research.google.com/github/suraj-gupta11/Machine-learning-lab/blob/main/Lab_2/ML2.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')




import pandas as pd
import numpy as np


file_path = "/content/drive/MyDrive/Lab Session Data.xlsx"
purchase_data = pd.read_excel(file_path)
purchase_data.head()




Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


,Customer,Candies (#),Mangoes (Kg),Milk Packets (#),Payment (Rs),Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Candy,Mango,Milk
0,C_1,20,6,2,386,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,55.0,18.0
1,C_2,16,3,6,289,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C_3,27,6,2,393,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,C_4,19,1,2,110,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,C_5,24,4,2,280,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [3]:
#feature of matrix X and output vector y

#Feature  matrix of X
X = purchase_data[["Candies (#)","Mangoes (Kg)", "Milk Packets (#)"]].values

# Output Vector y
y = purchase_data["Payment (Rs)"]

print("X matrix: ")
print(X)

print("\n y vector: ")
print(y)

X matrix: 
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]

 y vector: 
0    386
1    289
2    393
3    110
4    280
5    167
6    271
7    274
8    148
9    198
Name: Payment (Rs), dtype: int64


In [10]:
#Finnding the Rank of the matrix
rank = np.linalg.matrix_rank(X)
print("Rank of the feature Matrix X is: ", rank)



Rank of the feature Matrix X is:  3


In [11]:
#Using Pseudo-Inverse find the cost of each product available for sale
X_pseudo_inverse = np.linalg.pinv(X)
cost = X_pseudo_inverse.dot(y)

print("Cost of each Product")
print("Cost of Candies(#)",cost[0])
print("Cost of Mangoes (Kg)",cost[1])
print("Cost of Milk Packets (#)",cost[2])

Cost of each Product
Cost of Candies(#) 0.9999999999999989
Cost of Mangoes (Kg) 54.99999999999999
Cost of Milk Packets (#) 18.0
